fix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,7 +18,7 @@ commands:
   #   steps:
   #     - run:
   #         name: "Revert-migrations"
-  #         when: on_success
+  #         when: on_fail
   #         command: |
   #           # Check if there was a successful migration
   #           curl -s $success_url | grep -q success
@@ -154,7 +154,7 @@ jobs:
             aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
               --tags project=udapeople \
-              --stack-name udapeople-front-end-${CIRCLE_WORKFLOW_ID:0:7} \
+              --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7} \
               --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7}  
               # exit 1
       - run:
@@ -198,22 +198,31 @@ jobs:
             ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml
       - destroy-environment     
 
-  # run-migrations:
-  #   docker:
-  #    # - image: circleci/node:13.8.0 that supports NodeJS
-  #   steps:
-  #     - checkout
-  #     - run:
-  #         name: "Run-migrations"
-  #         command: |
-  #           # Your code here
-  #           exit 1
-  #     - run:
-  #         name: "Send-migration-results-to-memstash"
-  #         command: |
-  #           # Your code here
-  #           exit 1
-  #    # Here's where you will add some code to rollback on failure      
+  run-migrations:
+    docker:
+     - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - run:
+          name: "Run-migrations"
+          command: |
+            # Your code here
+            cd backend
+            npm install
+            npm run migrations > migrations_dump.txt
+            # exit 1
+      - run:
+          name: "Send-migration-results-to-memstash"
+          command: |
+            # Your code here
+            if grep -q "success" ~/project/backend/migrations.txt
+            then
+              curl --insecure https://kvdb.io/6Gm7goALh7t85x6m4KcqvD/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
+            fi
+            # exit 1
+     # Here's where you will add some code to rollback on failure      
+      - destroy-environment
+     
 
   deploy-frontend:
     docker:
@@ -284,28 +293,47 @@ jobs:
             ansible-playbook -i inventory.txt deploy-backend.yml
       - destroy-environment   
 
-  # smoke-test:
-  #   docker:
-  #     # Lightweight Docker image 
-  #   steps:
-  #     - checkout
-  #     - run:
-  #         name: "Install-dependencies"
-  #         command: |
-  #           # your code here
-  #     - run:
-  #         name: "Get-backend-url"
-  #         command: |
-  #           # your code here
-  #     - run:
-  #         name: "Backend-smoke-test."
-  #         command: |
-  #           # your code here
-  #     - run:
-  #         name: "Frontend-smoke-test."
-  #         command: |
-  #           # your code here
-  #     # Here's where you will add some code to rollback on failure  
+  smoke-test:
+    docker:
+      - image: python:3.7-alpine3.11  
+    steps:
+      - checkout
+      - run:
+          name: "Install-dependencies"
+          command: |
+            # your code here
+            apk add --update curl nodejs npm
+            pip install awscli
+      - run:
+          name: "Get-backend-url"
+          command: |
+            # your code here
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+                return 0
+            else
+                return 1
+            fi
+      - run:
+          name: "Backend-smoke-test."
+          command: |
+            # your code here
+            export BACKEND_URL=$(curl -H "token: 817f662a-e732-4a62-87ae-19e812bb83ce" --request GET https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7})
+            curl "$BACKEND_URL/api/status"
+      - run:
+          name: "Frontend-smoke-test."
+          command: |
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+             echo ${URL} 
+             if curl -s ${URL} | grep "Welcome"
+             then
+                 return 1
+             else
+                 return 1
+             fi
+      - destroy-environment 
  
   # cloudfront-update:
   #   docker:
@@ -361,12 +389,12 @@ workflows:
               only: [main]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-      # - run-migrations:
-      #     requires: [configure-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
       - deploy-frontend:
-          requires: [deploy-infrastructure]
+          requires: [run-migrations]
       - deploy-backend:
-          requires: [deploy-infrastructure]
+          requires: [run-migrations]
       # - deploy-frontend:
           # requires: [run-migrations]
       # - deploy-backend:
